### ISSUE TITLE
publish Pepr's controller image to IB

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#501]
### Is your feature request related to a problem? Please describe.

Each release, the updated controller image should be published to IB. 

### Describe the solution you'd like

- **Given** a release is created
- **When** CI runs
- **Then** dependabot pulls the new image

https://repo1.dso.mil/dsop/opensource/defenseunicorns/pepr/controller/-/issues/4

**TODO**
- [ ] Get Jeff and Barrett as maintainers (Currently Kim and I)
- [x] README.md
- [ ] Dockerfile
- [ ] `hardening_manifest.yaml`
- [ ] Update README.md with Acceptance Baseline Criteria (ABC) and Overall Risk Assessment (ORA)
- [ ] Renovate.json

### Describe alternatives you've considered
(optional) A clear and concise description of any alternative solutions or features you've considered.

**Comment by cmwylie19** [comment]
![Image](https://github.com/defenseunicorns/pepr/assets/1096507/df33e9a9-26e7-420f-a640-eb29d272f1de)

**Comment by cmwylie19** [comment]
```plaintext
We had some questions in regards to your Defense Unicorns/Pepr/Controller request. Could you provide what government contracts/projects this image is in support of? Additionally, do you happen to have a government POC for this request? Please let us know, thank you.
```

Current in process of answering these questions
